// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxBCLbv0JMC9JiRx9yzczMaEWy8RW-2Uc',
    appId: '1:446492818809:web:f299aa0dd25b9468f643a8',
    messagingSenderId: '446492818809',
    projectId: 'recuritmentproject',
    authDomain: 'recuritmentproject.firebaseapp.com',
    databaseURL: 'https://recuritmentproject-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'recuritmentproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi9jQYkeUIzE3SkqMY47Mwx1Zz1VO1_aA',
    appId: '1:446492818809:android:9cca3db1e3190c14f643a8',
    messagingSenderId: '446492818809',
    projectId: 'recuritmentproject',
    databaseURL: 'https://recuritmentproject-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'recuritmentproject.firebasestorage.app',
  );

}